In [1]:
# install the packages we need

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# load the data

NBA19 = pd.read_excel("Assignment Data/NBA2019odds.xlsx")
NBA19

,team,opponent,day,month,year,winodds,loseodds,teampts,oppopts,diff,overtime,home,Game(home-away),HAscore,win prob,win
0,Golden State Warriors,Houston Rockets,4,1,2019,1.27,3.92,134,135,1,1,1,Golden State Warriors - Houston Rockets,134:135 ET,0.755299,0
1,Houston Rockets,Golden State Warriors,4,1,2019,3.92,1.27,135,134,1,1,0,Golden State Warriors - Houston Rockets,134:135 ET,0.244701,1
2,New York Knicks,Washington Wizards,17,1,2019,3.52,1.32,100,101,1,0,0,Washington Wizards - New York Knicks,101:100,0.272727,0
3,Washington Wizards,New York Knicks,17,1,2019,1.32,3.52,101,100,1,0,1,Washington Wizards - New York Knicks,101:100,0.727273,1
4,Boston Celtics,Los Angeles Lakers,8,2,2019,1.24,4.31,128,129,1,0,1,Boston Celtics - Los Angeles Lakers,128:129,0.776577,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,Golden State Warriors,Charlotte Hornets,1,4,2019,1.13,6.42,137,90,47,0,1,Golden State Warriors - Charlotte Hornets,137:90,0.850331,1
2456,Dallas Mavericks,Utah Jazz,15,11,2018,2.75,1.47,118,68,50,0,1,Dallas Mavericks - Utah Jazz,118:68,0.348341,1
2457,Utah Jazz,Dallas Mavericks,15,11,2018,1.47,2.75,68,118,50,0,0,Dallas Mavericks - Utah Jazz,118:68,0.651659,0
2458,Boston Celtics,Chicago Bulls,9,12,2018,1.28,3.80,133,77,56,0,0,Chicago Bulls - Boston Celtics,77:133,0.748031,1


In [7]:
NBA19['winprob']= 1/(NBA19['winodds'])/(1/(NBA19['winodds'])+ 1/(NBA19['loseodds']))
NBA19

,team,opponent,day,month,year,winodds,loseodds,teampts,oppopts,diff,overtime,home,Game(home-away),HAscore,win prob,win,winprob
0,Golden State Warriors,Houston Rockets,4,1,2019,1.27,3.92,134,135,1,1,1,Golden State Warriors - Houston Rockets,134:135 ET,0.755299,0,0.755299
1,Houston Rockets,Golden State Warriors,4,1,2019,3.92,1.27,135,134,1,1,0,Golden State Warriors - Houston Rockets,134:135 ET,0.244701,1,0.244701
2,New York Knicks,Washington Wizards,17,1,2019,3.52,1.32,100,101,1,0,0,Washington Wizards - New York Knicks,101:100,0.272727,0,0.272727
3,Washington Wizards,New York Knicks,17,1,2019,1.32,3.52,101,100,1,0,1,Washington Wizards - New York Knicks,101:100,0.727273,1,0.727273
4,Boston Celtics,Los Angeles Lakers,8,2,2019,1.24,4.31,128,129,1,0,1,Boston Celtics - Los Angeles Lakers,128:129,0.776577,0,0.776577
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,Golden State Warriors,Charlotte Hornets,1,4,2019,1.13,6.42,137,90,47,0,1,Golden State Warriors - Charlotte Hornets,137:90,0.850331,1,0.850331
2456,Dallas Mavericks,Utah Jazz,15,11,2018,2.75,1.47,118,68,50,0,1,Dallas Mavericks - Utah Jazz,118:68,0.348341,1,0.348341
2457,Utah Jazz,Dallas Mavericks,15,11,2018,1.47,2.75,68,118,50,0,0,Dallas Mavericks - Utah Jazz,118:68,0.651659,0,0.651659
2458,Boston Celtics,Chicago Bulls,9,12,2018,1.28,3.80,133,77,56,0,0,Chicago Bulls - Boston Celtics,77:133,0.748031,1,0.748031


In [15]:
NBA19_team = NBA19.groupby('team')[['winprob','win']].mean()
NBA19_team

,winprob,win
team,,
Atlanta Hawks,0.392680,0.414634
Boston Celtics,0.706657,0.682927
Brooklyn Nets,0.526951,0.560976
Charlotte Hornets,0.595834,0.609756
Chicago Bulls,0.364127,0.219512
Cleveland Cavaliers,0.321675,0.317073
Dallas Mavericks,0.525763,0.585366
Denver Nuggets,0.715882,0.829268
Detroit Pistons,0.590888,0.634146


In [17]:
np.corrcoef(NBA19['win'],NBA19['winprob'])

array([[1.        , 0.39652887],
       [0.39652887, 1.        ]])

In [9]:
NBA19 = NBA19[NBA19['home']==1]
NBA19.shape

(1230, 17)

In [10]:
NBA19['diffpts'] = abs(NBA19['teampts'] - NBA19['oppopts'])
NBA19

,team,opponent,day,month,year,winodds,loseodds,teampts,oppopts,diff,overtime,home,Game(home-away),HAscore,win prob,win,winprob,diffpts
0,Golden State Warriors,Houston Rockets,4,1,2019,1.27,3.92,134,135,1,1,1,Golden State Warriors - Houston Rockets,134:135 ET,0.755299,0,0.755299,1
3,Washington Wizards,New York Knicks,17,1,2019,1.32,3.52,101,100,1,0,1,Washington Wizards - New York Knicks,101:100,0.727273,1,0.727273,1
4,Boston Celtics,Los Angeles Lakers,8,2,2019,1.24,4.31,128,129,1,0,1,Boston Celtics - Los Angeles Lakers,128:129,0.776577,0,0.776577,1
7,Dallas Mavericks,Portland Trail Blazers,10,2,2019,2.30,1.65,102,101,1,0,1,Dallas Mavericks - Portland Trail Blazers,102:101,0.417722,1,0.417722,1
11,Memphis Grizzlies,San Antonio Spurs,13,2,2019,3.57,1.32,107,108,1,0,1,Memphis Grizzlies - San Antonio Spurs,107:108,0.269939,0,0.269939,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2450,Milwaukee Bucks,Portland Trail Blazers,22,11,2018,1.33,3.48,143,100,43,0,1,Milwaukee Bucks - Portland Trail Blazers,143:100,0.723493,1,0.723493,43
2453,Denver Nuggets,Atlanta Hawks,16,11,2018,1.08,8.97,138,93,45,0,1,Denver Nuggets - Atlanta Hawks,138:93,0.892537,1,0.892537,45
2455,Golden State Warriors,Charlotte Hornets,1,4,2019,1.13,6.42,137,90,47,0,1,Golden State Warriors - Charlotte Hornets,137:90,0.850331,1,0.850331,47
2456,Dallas Mavericks,Utah Jazz,15,11,2018,2.75,1.47,118,68,50,0,1,Dallas Mavericks - Utah Jazz,118:68,0.348341,1,0.348341,50


In [11]:
NBA19_1 = NBA19[NBA19['diffpts']<9]
NBA19_2 = NBA19[NBA19['diffpts']>9]
NBA19_1.tail()

,team,opponent,day,month,year,winodds,loseodds,teampts,oppopts,diff,overtime,home,Game(home-away),HAscore,win prob,win,winprob,diffpts
1103,New York Knicks,Brooklyn Nets,9,12,2018,1.77,2.10,104,112,8,0,1,New York Knicks - Brooklyn Nets,104:112,0.542636,0,0.542636,8
1104,Philadelphia 76ers,Memphis Grizzlies,3,12,2018,1.39,3.11,103,95,8,0,1,Philadelphia 76ers - Memphis Grizzlies,103:95,0.691111,1,0.691111,8
1105,Phoenix Suns,Minnesota Timberwolves,16,12,2018,3.62,1.30,107,99,8,0,1,Phoenix Suns - Minnesota Timberwolves,107:99,0.264228,1,0.264228,8
1108,Portland Trail Blazers,Minnesota Timberwolves,9,12,2018,1.68,2.24,113,105,8,0,1,Portland Trail Blazers - Minnesota Timberwolves,113:105,0.571429,1,0.571429,8
1110,San Antonio Spurs,Denver Nuggets,27,12,2018,1.57,2.48,111,103,8,0,1,San Antonio Spurs - Denver Nuggets,111:103,0.612346,1,0.612346,8


In [23]:
np.corrcoef(NBA19_2019['winprob'],NBA19_2019['win'])

array([[1.        , 0.43797601],
       [0.43797601, 1.        ]])

In [12]:
NBA19_reg = NBA19[NBA19['overtime']==0]
NBA19_ot = NBA19[NBA19['overtime']==1]

In [14]:
NBA19_2018 = NBA19[NBA19['year']==2018]
NBA19_2019 = NBA19[NBA19['year']==2019]

In [ ]:
One for each month in the data (October to April)

In [24]:
NBA19_oct = NBA19[NBA19['month']==10]
NBA19_nov = NBA19[NBA19['month']==11]
NBA19_dec = NBA19[NBA19['month']==12]
NBA19_jan = NBA19[NBA19['month']==1]
NBA19_feb = NBA19[NBA19['month']==2]
NBA19_mar = NBA19[NBA19['month']==3]
NBA19_apr = NBA19[NBA19['month']==4]

In [25]:
np.corrcoef(NBA19_oct['winprob'],NBA19_oct['win'])

array([[1.       , 0.4132173],
       [0.4132173, 1.       ]])

In [26]:
np.corrcoef(NBA19_nov['winprob'],NBA19_nov['win'])

array([[1.        , 0.31889017],
       [0.31889017, 1.        ]])

In [27]:
np.corrcoef(NBA19_dec['winprob'],NBA19_dec['win'])

array([[1.        , 0.32183843],
       [0.32183843, 1.        ]])

In [28]:
np.corrcoef(NBA19_jan['winprob'],NBA19_jan['win'])

array([[1.       , 0.5035297],
       [0.5035297, 1.       ]])

In [29]:
np.corrcoef(NBA19_feb['winprob'],NBA19_feb['win'])

array([[1.        , 0.37928007],
       [0.37928007, 1.        ]])

In [30]:
np.corrcoef(NBA19_mar['winprob'],NBA19_mar['win'])

array([[1.        , 0.41270836],
       [0.41270836, 1.        ]])

In [31]:
np.corrcoef(NBA19_apr['winprob'],NBA19_apr['win'])

array([[1.       , 0.4554355],
       [0.4554355, 1.       ]])